apiVersion: v1
kind: Service
metadata:
  name: logging-service
spec:
  selector:
    app: logging-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: ClusterIP
  sessionAffinity: None